FREERTOS_PATH=../../FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/

CROSS_COMPILE =arm-none-eabi-
CC		= $(CROSS_COMPILE)gcc
LD		= $(CROSS_COMPILE)ld
AR		= $(CROSS_COMPILE)ar
AS		= $(CROSS_COMPILE)as
OC		= $(CROSS_COMPILE)objcopy
OD		= $(CROSS_COMPILE)objdump
SZ		= $(CROSS_COMPILE)size

CFLAGS	= 	-c -fno-common \
		-ffunction-sections \
		-fdata-sections \
		-Os \
		-mcpu=cortex-m3 \
		-mthumb \
                -g3 \
                -DSTM32F10X_LD_VL
#                -DSTM32F10X_MD

#LDSCRIPT= ld/stm32_rom.ld
LDSCRIPT= ../ld/stm32_flash.ld

LDFLAGS	=	--gc-sections,-T$(LDSCRIPT),-no-startup,-nostdlib

OCFLAGS	=	-Obinary

ODFLAGS	=	-S


OUTPUT_DIR = output

TARGET  = 	$(OUTPUT_DIR)/main


INCLUDE =   -I../\
	    -I./src/ \
	    -I../include \
	    -I../fw_lib/include\
	    -I$(FREERTOS_PATH)/include/ \
	    -I$(FREERTOS_PATH)/portable/GCC/ARM_CM3/ \
	    -I../common


# Add other source files if they are needed e.g. other Firmwarlib Components
SRCS	=   ./src/main.c \
	    ../common/usart_stm32.c \
		$(FREERTOS_PATH)/timers.c \
		$(FREERTOS_PATH)/portable/MemMang/heap_4.c \
		$(FREERTOS_PATH)/portable/GCC/ARM_CM3/port.c \
		$(FREERTOS_PATH)/tasks.c \
		$(FREERTOS_PATH)/queue.c \
		$(FREERTOS_PATH)/croutine.c \
		$(FREERTOS_PATH)/list.c \
                ../fw_lib/system_stm32f10x.c \
                ../fw_lib/stm32f10x_it.c \
		../fw_lib/stm32f10x_rcc.c \
		../fw_lib/core_cm3.c \
		../fw_lib/stm32f10x_gpio.c \
		../fw_lib/stm32f10x_adc.c \
		../fw_lib/stm32f10x_usart.c \
#            $(FREERTOS_PATH)/syscalls.c \

OBJS=$(SRCS:.c=.o)


.PHONY : clean all


all: $(TARGET).bin  $(TARGET).list
	@echo "  SIZE $(TARGET).elf"
	$(SZ) $(TARGET).elf


clean:
	@echo "Removing files..."
	-find . -name '*.o'   | xargs rm
	-find $(FREERTOS_PATH) -name '*.o'   | xargs rm
	-find . -name '*.elf' | xargs rm
	-find . -name '*.lst' | xargs rm
	-find . -name '*.out' | xargs rm
	-find . -name '*.bin' | xargs rm
	-find . -name '*.map' | xargs rm
	rm ../common/*.o


$(TARGET).list: $(TARGET).elf
	@echo "  OBJDUMP $(TARGET).list"
	$(OD) $(ODFLAGS) $< > $(TARGET).lst



$(TARGET).bin: $(TARGET).elf
	@echo "  OBJCOPY $(TARGET).bin"
	$(OC) $(OCFLAGS) $(TARGET).elf $(TARGET).bin



$(TARGET).elf: $(OBJS) ../fw_lib/startup.o
	@echo "  LD $(TARGET).elf"
	$(CC) -mcpu=cortex-m3 -mthumb -Wl,$(LDFLAGS),-o$(TARGET).elf,-Map,$(TARGET).map ../fw_lib/startup.o $(OBJS)


%.o: %.c
	@echo "  CC $<"
	$(CC) $(INCLUDE) $(CFLAGS)  $< -o $*.o

%.o: %.S
	@echo "  CC $<"
	$(CC) $(INCLUDE) $(CFLAGS)  $< -o $*.o
