FREERTOS_PATH=/home/jmfriedt/enseignement/sqnx/platforms/stm32/F1/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/
FREERTOS_BSP=/home/jmfriedt/enseignement/sqnx/platforms/stm32/F1/FreeRTOS/FreeRTOS/Demo/

CROSS_COMPILE =arm-none-eabi-
CC		= $(CROSS_COMPILE)gcc
LD		= $(CROSS_COMPILE)ld
AR		= $(CROSS_COMPILE)ar
AS		= $(CROSS_COMPILE)as
OC		= $(CROSS_COMPILE)objcopy
OD		= $(CROSS_COMPILE)objdump
SZ		= $(CROSS_COMPILE)size

CFLAGS	= 	-c -fno-common \
		-ffunction-sections \
		-fdata-sections \
		-Os \
                -ggdb \
		-mcpu=cortex-a9 -mtune=cortex-a9 -mfloat-abi=hard 
#		-mthumb \

LDSCRIPT= $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/RTOSDemo/src/lscript.ld 
# -T ../common/redpitaya-baremetal/bsp/Zynq.ld

LDFLAGS	= --static -ggdb \
	-Wl,--start-group -lc -lgcc -lnosys -Wl,--end-group \
	-T$(LDSCRIPT) -nostartfiles \
        -Wl,--gc-sections \
        -L$(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/RTOSDemo_bsp/ps7_cortexa9_0/lib/ \
	-mcpu=cortex-a9 -mtune=cortex-a9 -mfloat-abi=hard -lxil
#	-mthumb \

OCFLAGS	=   -Obinary

OUTPUT_DIR = output

TARGET  = 	$(OUTPUT_DIR)/main


INCLUDE =   -I../\
	    -I./src/ \
	    -I$(FREERTOS_PATH)/include \
	    -I$(FREERTOS_PATH)/portable/GCC/ARM_CA9/ \
	    -I../common \
            -I $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/RTOSDemo_bsp/ps7_cortexa9_0/include \
            -I $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/MicroZed_hw_platform/  \
            -I $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/RTOSDemo/src

# Add other source files if they are needed e.g. other Firmwarlib Components
SRCS	=   ./src/main.c \
	    ../common/usart_redpit.c \
            $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/MicroZed_hw_platform/ps7_init_gpl.c \
	    $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/RTOSDemo/src/platform.c \
            ../common/redpitaya-baremetal/bsp/boot.S \
	    $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/RTOSDemo/src/FreeRTOS_asm_vectors.S \
	    $(FREERTOS_BSP)/CORTEX_A9_Zynq_ZC702/RTOSDemo/src/FreeRTOS_tick_config.c \
		$(FREERTOS_PATH)/timers.c \
		$(FREERTOS_PATH)/portable/MemMang/heap_4.c \
		$(FREERTOS_PATH)/portable/GCC/ARM_CA9/port.c \
		$(FREERTOS_PATH)/portable/GCC/ARM_CA9/portASM.S \
		$(FREERTOS_PATH)/tasks.c \
		$(FREERTOS_PATH)/queue.c \
		$(FREERTOS_PATH)/croutine.c \
		$(FREERTOS_PATH)/list.c 
#            ../common/redpitaya-baremetal/bsp/ps7_init_gpl.c \
#            ../common/redpitaya-baremetal/bsp/ps7_spl_init.c \

OBJS=$(SRCS:.c=.o)

.PHONY : clean all

all: $(TARGET).bin
	@echo "  SIZE $(TARGET).elf"
	$(SZ) $(TARGET).elf

clean:
	@echo "Removing files..."
	-find . -name '*.o'   | xargs rm
	-find $(FREERTOS_PATH) -name '*.o'   | xargs rm
	-find . -name '*.elf' | xargs rm
	-find . -name '*.lst' | xargs rm
	-find . -name '*.out' | xargs rm
	-find . -name '*.bin' | xargs rm
	-find . -name '*.map' | xargs rm
	rm ../common/*.o
	rm ../common/redpitaya-baremetal/bsp/*.o

$(TARGET).bin: $(TARGET).elf
	@echo "  OBJCOPY $(TARGET).bin"
	$(OC) $(OCFLAGS) $(TARGET).elf $(TARGET).bin

$(TARGET).elf: $(OBJS) 
	@echo "  LD $(TARGET).elf"
	$(CC) $(INCLUDE) -o $(TARGET).elf $(OBJS) $(LDFLAGS)

%.o: %.c src/FreeRTOSConfig.h
	@echo "  CC $<"
	$(CC) $(INCLUDE) $(CFLAGS)  $< -o $*.o

%.o: %.S src/FreeRTOSConfig.h
	@echo "  CC $<"
	$(CC) $(INCLUDE) $(CFLAGS)  $< -o $*.o

qemu: output/main.bin
	qemu-system-arm -s -S -M xilinx-zynq-a9 -serial mon:stdio -nographic -kernel output/main.bin
#	qemu-system-arm -M xilinx-zynq-a9 -serial mon:stdio -nographic -kernel output/main.bin


